server:
    port: 0
spring:
    yarn:
        endpoints:
            containercluster:
                enabled: true
        appmaster:
            appmasterClass: org.springframework.xd.yarn.XdAppmaster
            keepContextAlive: true
            localizer:
                patterns:
                    - "spring-xd-yarn*.zip"
                    - "servers.yml"
                    - "xd-admin-logger.properties"
                    - "xd-container-logger.properties"
                    - "modules-config.zip"
                    - "custom-modules.zip"
            containercluster:
                enabled: true
                clusters:
                    admin:
                        projection:
                            type: default
                            data:
                                any: "${xd.adminServers:1}"
                        resource:
                            priority: 1
                            memory: "${xd.adminMemory:512M}"
                            virtualCores: 1
                        launchcontext:
                            runnerClass: org.springframework.xd.dirt.server.admin.AdminServerApplication
                            locality: "${xd.adminLocality:false}"
                            useYarnAppClasspath: true
                            useMapreduceAppClasspath: true
                            options:
                                - "${xd.adminJavaOpts:}"
                            arguments:
                                -Dspring.application.name: "admin"
                                -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                                -Dspring.config.location: "./servers.yml"
                                -Dlogging.config: "./xd-admin-logger.properties"
                                -Dxd.module.config.location: "file:./modules-config.zip/"
                            containerAppClasspath:
                                - "./${spring.xd.yarn.app.zip}/config"
                                - "./${spring.xd.yarn.app.zip}/lib/*"
                                - "./custom-modules.zip"
                    container:
                        projection:
                            type: default
                            data:
                                any: "${xd.containers:1}"
                        resource:
                            priority: 2
                            memory: "${xd.containerMemory:512M}"
                            virtualCores: 1
                        launchcontext:
                            runnerClass: org.springframework.xd.dirt.server.container.ContainerServerApplication
                            locality: "${xd.containerLocality:false}"
                            useYarnAppClasspath: true
                            useMapreduceAppClasspath: true
                            options:
                                - "${xd.containerJavaOpts:}"
                            arguments:
                                -Dspring.application.name: "container"
                                -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                                -Dspring.config.location: "./servers.yml"
                                -Dlogging.config: "./xd-container-logger.properties"
                                -Dxd.module.config.location: "file:./modules-config.zip/"
                                -Dxd.container.groups: "${xd.container.groups:yarn}"
                            containerAppClasspath:
                                - "./${spring.xd.yarn.app.zip}/config"
                                - "./${spring.xd.yarn.app.zip}/lib/*"
                                - "./${spring.xd.yarn.app.zip}/modules/processor/scripts"
                                - "./custom-modules.zip/modules/processor/scripts"
                                - "./custom-modules.zip"
                    admin-nolocality-template:
                        resource:
                            priority: 10
                            memory: "${xd.adminMemory:512M}"
                            virtualCores: 1
                        launchcontext:
                            runnerClass: org.springframework.xd.dirt.server.admin.AdminServerApplication
                            locality: false
                            useYarnAppClasspath: true
                            useMapreduceAppClasspath: true
                            options:
                                - "${xd.adminJavaOpts:}"
                            arguments:
                                -Dspring.application.name: "admin"
                                -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                                -Dspring.config.location: "./servers.yml"
                                -Dlogging.config: "./xd-admin-logger.properties"
                                -Dxd.module.config.location: "file:./modules-config.zip/"
                            containerAppClasspath:
                                - "./${spring.xd.yarn.app.zip}/config"
                                - "./${spring.xd.yarn.app.zip}/lib/*"
                                - "./custom-modules.zip"
                    admin-locality-template:
                        resource:
                            priority: 20
                            memory: "${xd.adminMemory:512M}"
                            virtualCores: 1
                        launchcontext:
                            runnerClass: org.springframework.xd.dirt.server.admin.AdminServerApplication
                            locality: true
                            useYarnAppClasspath: true
                            useMapreduceAppClasspath: true
                            options:
                                - "${xd.adminJavaOpts:}"
                            arguments:
                                -Dspring.application.name: "admin"
                                -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                                -Dspring.config.location: "./servers.yml"
                                -Dlogging.config: "./xd-admin-logger.properties"
                                -Dxd.module.config.location: "file:./modules-config.zip/"
                            containerAppClasspath:
                                - "./${spring.xd.yarn.app.zip}/config"
                                - "./${spring.xd.yarn.app.zip}/lib/*"
                                - "./custom-modules.zip"
                    container-nolocality-template:
                        resource:
                            priority: 30
                            memory: "${xd.containerMemory:512M}"
                            virtualCores: 1
                        launchcontext:
                            runnerClass: org.springframework.xd.dirt.server.container.ContainerServerApplication
                            locality: false
                            useYarnAppClasspath: true
                            useMapreduceAppClasspath: true
                            options:
                                - "${xd.containerJavaOpts:}"
                            arguments:
                                -Dspring.application.name: "container"
                                -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                                -Dspring.config.location: "./servers.yml"
                                -Dlogging.config: "./xd-container-logger.properties"
                                -Dxd.module.config.location: "file:./modules-config.zip/"
                                -Dxd.container.groups: "${xd.container.groups:yarn}"
                            containerAppClasspath:
                                - "./${spring.xd.yarn.app.zip}/config"
                                - "./${spring.xd.yarn.app.zip}/lib/*"
                                - "./${spring.xd.yarn.app.zip}/modules/processor/scripts"
                                - "./custom-modules.zip/modules/processor/scripts"
                                - "./custom-modules.zip"
                    container-locality-template:
                        resource:
                            priority: 40
                            memory: "${xd.containerMemory:512M}"
                            virtualCores: 1
                        launchcontext:
                            runnerClass: org.springframework.xd.dirt.server.container.ContainerServerApplication
                            locality: true
                            useYarnAppClasspath: true
                            useMapreduceAppClasspath: true
                            options:
                                - "${xd.containerJavaOpts:}"
                            arguments:
                                -Dspring.application.name: "container"
                                -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                                -Dspring.config.location: "./servers.yml"
                                -Dlogging.config: "./xd-container-logger.properties"
                                -Dxd.module.config.location: "file:./modules-config.zip/"
                                -Dxd.container.groups: "${xd.container.groups:yarn}"
                            containerAppClasspath:
                                - "./${spring.xd.yarn.app.zip}/config"
                                - "./${spring.xd.yarn.app.zip}/lib/*"
                                - "./${spring.xd.yarn.app.zip}/modules/processor/scripts"
                                - "./custom-modules.zip/modules/processor/scripts"
                                - "./custom-modules.zip"
